### ISSUE TITLE
ClusterID may not be needed as an input

### ISSUE THREAD

**Issue by comtalyst** [Azure/karpenter-provider-azure#130]
### Tell us about your request

`ClusterID` is currently an optional input from the user. If not provided, a randomized ID will be generated based on `ClusterEndpoint`. However, it may not be useful for user to provide it.
Had an additional discussion offline.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Evaluate the idea of removing the ability to provide `ClusterID` from the interface.

### Are you currently working around this issue?

Yes

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by krkeshav** [comment]
Hi I am interested in working on this issue.

**Comment by Bryce-Soghigian** [comment]
Hey Keshav! Excited to see your interest in the project. Please feel free to ask questions here aboout the problem.

**Comment by krkeshav** [comment]
#169 Added PR for this issue
