### ISSUE TITLE
InstanceTypes Provider should cache instance types by image family

### ISSUE THREAD

**Issue by Bryce-Soghigian** [Azure/karpenter-provider-azure#193]
### Tell us about your request

We should be caching the instance types by image family  rather than recalcuating on the full list each time.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

WE want to get the instance types by image family as well in the cache. 

https://github.com/Azure/karpenter-provider-azure/blob/main/pkg/providers/instancetype/instancetypes.go#L73
```go
// Get all instance type options
func (p *Provider) List(
	ctx context.Context, kc *corev1beta1.KubeletConfiguration, nodeClass *v1alpha2.AKSNodeClass) ([]*cloudprovider.InstanceType, error) {
	p.Lock()
	defer p.Unlock()
	// Get SKUs from Azure
	skus, err := p.getInstanceTypes(ctx)
	if err != nil {
		return nil, err
	}

	// Get Viable offerings
	/// Azure has zones availability directly from SKU info
	var result []*cloudprovider.InstanceType
	for _, sku := range skus {
		vmsize, err := sku.GetVMSize()
		if err != nil {
			logging.FromContext(ctx).Errorf("parsing VM size %s, %v", *sku.Size, err)
			continue
		}
		architecture, err := sku.GetCPUArchitectureType()
		if err != nil {
			logging.FromContext(ctx).Errorf("parsing SKU architecture %s, %v", *sku.Size, err)
			continue
		}
		instanceTypeZones := instanceTypeZones(sku, p.region)
		instanceType := NewInstanceType(ctx, sku, vmsize, kc, p.region, p.createOfferings(sku, instanceTypeZones), nodeClass, architecture)
		if len(instanceType.Offerings) == 0 {
			continue
		}

		if !p.isInstanceTypeSupportedByImageFamily(sku.GetName(), lo.FromPtr(nodeClass.Spec.ImageFamily)) {
			continue
		}
		result = append(result, instanceType)
	}
	return result, nil
}
```

### Are you currently working around this issue?

No

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tallaxes** [comment]
So, this has the right idea (there should indeed be caching to avoid recalculating every time; and image family, being one of the inputs affecting the resulting set of instance types for a given NodePool, should indeed be part of the overall cache key), but:
* This needs to be done at a (new) higher level cache, which would cache the _fully initialized_ instance type list for a given NodePool. (#194 still leaves a lot of additional processing required on every List call; and that's where one would expect the most perf gains.)
* The existing lower level cache (in getInstanceTypes) should stay the same, representing all (NodePool-independent) instance types Karpenter can work with. It is there essentially to reduce skewer / resource API calls. It should also have a version (mediated by change monitor), that NodePool-specific cache can use. (#194 messes with that lower-level / API cache; will also store a lot of duplicate instance types per image family)
* Image family is not the only additional input affecting the resulting set of instance types for a given NodePool. There are additional fields from NodePool (kubelet config) and AKSNodeClass (OSDiskSize) that need to be included in the key. (There may be others, but those stand out.)
* Note that the (version of) unavailable offerings cache is yet another input, and should be included as well. (We need to add versioning support to that cache).

Here as well, AWS provider implementation can serve as a reference. Note the implementation of cache versioning (via SeqNum; guarded by ChangeMonitor where needed), composition of the synthetic key, etc.

**Comment by tallaxes** [comment]
Was considering repurposing this issue for the above, but decided a separate one makes more sense; created https://github.com/Azure/karpenter-provider-azure/issues/226, copied the above requirements, let's flesh it out further there.
