### ISSUE TITLE
ACR image pull failed for nodes provisioned by node auto provisioner

### ISSUE THREAD

**Issue by SinglaSandeep** [Azure/karpenter-provider-azure#197]
### Version

AKS version : 1.26.10

### Expected Behavior

Below is expected behavior:
1) Pods are in pending state
2) Based on node pool configuration, Node auto provisioner should provision new nodes  & node should join the AKS cluster
3) Pod should be scheduled on the new node.
4) Pod image get pulled from ACR.
5) Pod starts

### Actual Behavior

1) Pods are in pending state
2) Based on node pool configuration, Node auto provisioner provision new nodes  & node join the AKS cluster
3) Pod get scheduled on the new node.
4) Although kubelet identity has ACR image pull role assigned still image pull fails for pods scheduled on node provisioned by karpenter. No error observed on system nodepools.

Failed to pull image "<ACR>.azurecr.io/ms-aks-demo:latest": [rpc error: code = Unknown desc = failed to pull and unpack image "<ACR>.azurecr.io/ms-aks-demo:latest": failed to resolve reference "<ACR>..azurecr.io/ms-aks-demo:latest": failed to authorize: failed to fetch oauth token: unexpected status from GET request to https://<ACR>.azurecr.io/oauth2/token?scope=repository%3Ams-aks-demo%3Apull&service=<ACR>.azurecr.io: 401 Unauthorized, rpc error: code = Unknown desc = failed to pull and unpack image "<ACR>.azurecr.io/ms-aks-demo:latest": failed to resolve reference "<ACR>.azurecr.io/ms-aks-demo:latest": failed to authorize: failed to fetch anonymous token: unexpected status from
   GET request to https://<ACR>.azurecr.io/oauth2/token?scope=repository%3Ams-aks-demo%3Apull&service=<ACR>.azurecr.io: 401 Unauthorized]

### Steps to Reproduce the Problem

1) Create AKS cluster and enable node auto provisioning
https://learn.microsoft.com/en-us/azure/aks/node-autoprovision?tabs=azure-cli#enable-node-autoprovisioning
2) Attach ACR to AKS cluster
https://learn.microsoft.com/en-us/azure/aks/cluster-container-registry-integration?tabs=azure-cli#attach-an-acr-to-an-existing-aks-cluster
3) Create new nodepool definition
4) Create deployment so that pods are scheduled on new nodes provisioned by nap & container image is pulled from ACR.

### Resource Specs and Logs

Failed to pull image "<ACR>.azurecr.io/ms-aks-demo:latest": [rpc error: code = Unknown desc = failed to pull and unpack image "<ACR>.azurecr.io/ms-aks-demo:latest": failed to resolve reference "<ACR>..azurecr.io/ms-aks-demo:latest": failed to authorize: failed to fetch oauth token: unexpected status from GET request to https://<ACR>.azurecr.io/oauth2/token?scope=repository%3Ams-aks-demo%3Apull&service=<ACR>.azurecr.io: 401 Unauthorized, rpc error: code = Unknown desc = failed to pull and unpack image "<ACR>.azurecr.io/ms-aks-demo:latest": failed to resolve reference "<ACR>.azurecr.io/ms-aks-demo:latest": failed to authorize: failed to fetch anonymous token: unexpected status from
   GET request to https://<ACR>.azurecr.io/oauth2/token?scope=repository%3Ams-aks-demo%3Apull&service=<ACR>.azurecr.io: 401 Unauthorized]

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by comtalyst** [comment]
I found some clues and will take a look at this

**Comment by MarkWme** [comment]
Hi - came across this issue today and did a little more digging. Tried using AKS clusters deployed with both system and user assigned managed identity for both the control plane and the kubelet and in both cases it fails as above. However, creating a service principal, assigning ACR-Pull role, creating a K8s secret and then referencing that secret in the deployment yaml works. So, this appears to be a problem with the nodes that Karpenter creates and managed identity. Is the kubelet using the wrong identity?

**Comment by comtalyst** [comment]
@MarkWme Thanks for the insight. Karpenter-provisioned nodes having wrong kubelet identity is also prime suspect on my side.

**Comment by comtalyst** [comment]
We found a potential root cause and fix for the issue (see the PR for more details). 
Will keep you all updated on the official version cuts and rollout for NAP if this fix is accepted.
