### ISSUE TITLE
BYO CNI support

### ISSUE THREAD

**Issue by flbla** [Azure/karpenter-provider-azure#270]
### Tell us about your request

Hi,
it seems byo cni (https://learn.microsoft.com/en-us/azure/aks/use-byo-cni?tabs=azure-cli) is not supported by karpenter-provider-azure

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

I would like to install my own CNI and be able to use Karpenter

### Are you currently working around this issue?

no

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Bryce-Soghigian** [comment]
Could you explain a bit more about your usecase?

**Comment by flbla** [comment]
Hi @Bryce-Soghigian ,
We deploy AKS clusters with BYO CNI.
We would like to start using Karpenter on it.
It looks like it's not possible for now.

**Comment by ppodevlabs** [comment]
we are in the same situation:

AKS cluster with BYO CNI, using calico at the moment, according to the docs it is not supported.

**Comment by tallaxes** [comment]
Support introduced in https://github.com/Azure/karpenter-provider-azure/pull/365
