### ISSUE TITLE
mcr.microsoft.com/aks/karpenter/karpenter:v0.3.0: not found

### ISSUE THREAD

**Issue by ottodeng** [Azure/karpenter-provider-azure#278]
### Version

(base) ottodeng@Otto-MacBook-Pro-M2.local:/Users/ottodeng/aks/self-host/karpenter-provider-azure/hack/deploy git:(main*) $ export KARPENTER_VERSION=v0.3.0

helm upgrade --install karpenter oci://mcr.microsoft.com/aks/karpenter/karpenter \
  --version "${KARPENTER_VERSION}" \
  --namespace "${KARPENTER_NAMESPACE}" --create-namespace \
  --values karpenter-values.yaml \
  --set controller.resources.requests.cpu=1 \
  --set controller.resources.requests.memory=1Gi \
  --set controller.resources.limits.cpu=1 \
  --set controller.resources.limits.memory=1Gi \
  --wait

kubectl logs -f -n "${KARPENTER_NAMESPACE}" -l app.kubernetes.io/name=karpenter -c controller
Release "karpenter" does not exist. Installing it now.
Error: mcr.microsoft.com/aks/karpenter/karpenter:v0.3.0: not found
No resources found in kube-system namespace.

### Expected Behavior

follow main brach to deploy self host NAP. something missing.

### Actual Behavior

export KARPENTER_VERSION=v0.3.0

helm upgrade --install karpenter oci://mcr.microsoft.com/aks/karpenter/karpenter \
  --version "${KARPENTER_VERSION}" \
  --namespace "${KARPENTER_NAMESPACE}" --create-namespace \
  --values karpenter-values.yaml \
  --set controller.resources.requests.cpu=1 \
  --set controller.resources.requests.memory=1Gi \
  --set controller.resources.limits.cpu=1 \
  --set controller.resources.limits.memory=1Gi \
  --wait

kubectl logs -f -n "${KARPENTER_NAMESPACE}" -l app.kubernetes.io/name=karpenter -c controller
Release "karpenter" does not exist. Installing it now.
Error: mcr.microsoft.com/aks/karpenter/karpenter:v0.3.0: not found

### Steps to Reproduce the Problem

export KARPENTER_VERSION=v0.3.0

helm upgrade --install karpenter oci://mcr.microsoft.com/aks/karpenter/karpenter \
  --version "${KARPENTER_VERSION}" \
  --namespace "${KARPENTER_NAMESPACE}" --create-namespace \
  --values karpenter-values.yaml \
  --set controller.resources.requests.cpu=1 \
  --set controller.resources.requests.memory=1Gi \
  --set controller.resources.limits.cpu=1 \
  --set controller.resources.limits.memory=1Gi \
  --wait

kubectl logs -f -n "${KARPENTER_NAMESPACE}" -l app.kubernetes.io/name=karpenter -c controller
Release "karpenter" does not exist. Installing it now.
Error: mcr.microsoft.com/aks/karpenter/karpenter:v0.3.0: not found

### Resource Specs and Logs

Error: mcr.microsoft.com/aks/karpenter/karpenter:v0.3.0: not found

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tallaxes** [comment]
The readme is a little ahead of the release, the described flow will start working from the next release (likely 0.4.0), will be cut within a week (and we will update the readme). Meanwhile, the readme section describing how to install snapshot version should be working fine, and is referencing a very recent commit; please give it a try.

**Comment by ottodeng** [comment]
@tallaxes any where can check the helm version list or always available version?
yesterday the snapshot version works, but today not available again.

Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  22s               default-scheduler  Successfully assigned kube-system/karpenter-555bf7479-fn2sj to aks-nodepool1-27538885-vmss000002
  Normal   BackOff    19s               kubelet            Back-off pulling image "ksnap.azurecr.io/karpenter/snapshot/controller:f83fadf2c99ffc2b7429cb40a316fcefc0c4752a@sha256:94a5b156f64f46c0d9811fab7b8b9388e6db904cb3b299bdd380868d78a979e9"
  Warning  Failed     19s               kubelet            Error: ImagePullBackOff
  Normal   Pulling    5s (x2 over 21s)  kubelet            Pulling image "ksnap.azurecr.io/karpenter/snapshot/controller:f83fadf2c99ffc2b7429cb40a316fcefc0c4752a@sha256:94a5b156f64f46c0d9811fab7b8b9388e6db904cb3b299bdd380868d78a979e9"
  Warning  Failed     2s (x2 over 19s)  kubelet            Failed to pull image "ksnap.azurecr.io/karpenter/snapshot/controller:f83fadf2c99ffc2b7429cb40a316fcefc0c4752a@sha256:94a5b156f64f46c0d9811fab7b8b9388e6db904cb3b299bdd380868d78a979e9": rpc error: code = NotFound desc = failed to pull and unpack image "ksnap.azurecr.io/karpenter/snapshot/controller@sha256:94a5b156f64f46c0d9811fab7b8b9388e6db904cb3b299bdd380868d78a979e9": failed to resolve reference "ksnap.azurecr.io/karpenter/snapshot/controller@sha256:94a5b156f64f46c0d9811fab7b8b9388e6db904cb3b299bdd380868d78a979e9": ksnap.azurecr.io/karpenter/snapshot/controller@sha256:94a5b156f64f46c0d9811fab7b8b9388e6db904cb3b299bdd380868d78a979e9: not found
  Warning  Failed     2s (x2 over 19s)  kubelet            Error: ErrImagePull

**Comment by tallaxes** [comment]
Please try again (may need to redeploy, including pulling Helm chart). It looks like artifact GC for snapshots is over-zealous, should be keeping them for 30 days, but does not.  The release artifacts won't be GC'ed, so just need to switch to release version - once released (in next couple of days).

**Comment by tallaxes** [comment]
Update: We published 0.4.0 release, and updated the readme. Please give it a try, and let us know / reopen this issue if you run into any problems.
