### ISSUE TITLE
v0.4.0-rc.3 running snapshot.sh gives an unbound variable error

### ISSUE THREAD

**Issue by uniemimu** [Azure/karpenter-provider-azure#294]
### Version

__Karpenter Version:__ v0.4.0-rc.3

__Kubernetes Version:__ v1.0.0

### Expected Behavior

The script used to work.

### Actual Behavior

/src/karpenter-provider-azure/hack/release/common.sh: line 88: $5: unbound variable

A recent commit changed the common.sh buildAndPublish -function $5 handling so that it now gives an unbound variable error when the function is called from snapshot. You could for example drop the "u" from the "set -euo" or then the buildAndPublish needs a revisit or you could send an extra empty function argument from the function snapshot.

### Steps to Reproduce the Problem

try running make snapshot
@charliedmcb

### Resource Specs and Logs

Does not build

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by charliedmcb** [comment]
Thanks for finding this, and letting me know! I'll get right on a fix.
