### ISSUE TITLE
User assigned managed identity for nodes

### ISSUE THREAD

**Issue by tpaul1611** [Azure/karpenter-provider-azure#299]
### Tell us about your request

Is there a way how to assign a managed identity to the nodes that karpenter is provisioning?

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Some of the services that we are currently deploying in AKS are consuming the nodepool managed idenity. We would need this ID to be also assigned to the nodes managed by karpenter.

### Are you currently working around this issue?

I did not find a solution for this yet.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tallaxes** [comment]
Is this about NAP or self-hosted Karpenter? (We should add this question to the template ...) Self-hosted Karpenter accepts a list of additional node identities via `--node-identities` flag or `NODE_IDENTITIES` environment variable. This is not documented well, and also not part of standard chart values - but you should be able to pass it in via `controller.env`. Please give this a try and let us know.

**Comment by tallaxes** [comment]
https://github.com/Azure/karpenter-provider-azure/pull/301 (an attempt to fix https://github.com/Azure/karpenter-provider-azure/issues/300) illustrates the capability

**Comment by tpaul1611** [comment]
@tallaxes I am using self-hosted Karpenter. I am just trying this out, what format are the identities to be configured in for the controller.env? Is it comma seperated list of arm IDs, or client-ids?

**Comment by tallaxes** [comment]
Comma separated list of ARM IDs

**Comment by tpaul1611** [comment]
Awesome it worked :)

**Comment by bharath300** [comment]
Does NAP also provide configuration options for adding user assigned managed identity for nodes?
