### ISSUE TITLE
node created by karpenter, cannot pull ACR image.

### ISSUE THREAD

**Issue by ottodeng** [Azure/karpenter-provider-azure#300]
### Version

__Karpenter Version:__ v0.4.0

__Kubernetes Version:__ v1.27.9

### Expected Behavior

node can pull ACR image.

### Actual Behavior

Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  12m                   default-scheduler  0/10 nodes are available: 10 Insufficient nvidia.com/gpu. preemption: 0/10 nodes are available: 10 No preemption victims found for incoming pod..
  Warning  FailedScheduling  11m                   default-scheduler  0/10 nodes are available: 10 Insufficient nvidia.com/gpu. preemption: 0/10 nodes are available: 10 No preemption victims found for incoming pod..
  Normal   Scheduled         7m5s                  default-scheduler  Successfully assigned default/nginx-deployment-5bbff74cf8-79pmf to aks-t4-spot-pgpck
  Normal   Nominated         8m9s (x3 over 12m)    karpenter          Pod should schedule on: nodeclaim/t4-spot-npr4z
  Normal   Pulling           5m45s (x4 over 7m5s)  kubelet            Pulling image "ottoacr.azurecr.io/nginx:v1"
  Warning  Failed            5m45s (x4 over 7m5s)  kubelet            Failed to pull image "ottoacr.azurecr.io/nginx:v1": rpc error: code = Unknown desc = failed to pull and unpack image "ottoacr.azurecr.io/nginx:v1": failed to resolve reference "ottoacr.azurecr.io/nginx:v1": failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ottoacr.azurecr.io/oauth2/token?scope=repository%3Anginx%3Apull&service=ottoacr.azurecr.io: 401 Unauthorized
  Warning  Failed            5m45s (x4 over 7m5s)  kubelet            Error: ErrImagePull
  Warning  Failed            5m18s (x6 over 7m4s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff           118s (x20 over 7m4s)  kubelet            Back-off pulling image "ottoacr.azurecr.io/nginx:v1"

![image](https://github.com/Azure/karpenter-provider-azure/assets/20509364/de84f57e-cb04-4339-8122-0470d60575f7)

Only classic nodepool can pull ACR image, because the managed identity bind vmss.
But karpenter node don't have any identiy, karpentermsi don't bind it.

### Steps to Reproduce the Problem

az aks update -n karpenter -g karpenter  --attach-acr ottoacr

### Resource Specs and Logs

Back-off pulling image "ottoacr.azurecr.io/nginx:v1"

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tallaxes** [comment]
Are you using self-hosted Karpenter or NAP? If NAP, I am wondering if this could be a duplicate of https://github.com/Azure/karpenter-provider-azure/issues/197 (fixed, but not rolled out yet).

**Comment by ottodeng** [comment]
> Are you using self-hosted Karpenter or NAP? If NAP, I am wondering if this could be a duplicate of https://github.com/Azure/karpenter-provider-azure/issues/197 (fixed, but not rolled out yet).

I use self-hosted Karpenter, can updated the v0.4.0 version.

**Comment by tallaxes** [comment]
I think you are right, we should be propagating at least agentpool identity into node identities. Here is a draft PR which has the updated create-values and karpenter-values-template: https://github.com/Azure/karpenter-provider-azure/pull/301. I won't be able to test it until later, but give it a try if you have a chance.

**Comment by tallaxes** [comment]
@ottodeng We are fairly certain #301 fixes this, please retest (and re-open this issue if needed)

**Comment by ATymus** [comment]
Hello,
I have updated to version 0.5.0, and the managed identity has been added to the VM. However, the issue persists. The node created by Karpenter still cannot pull the ACR image and shows a 401 error.

Here are the steps I've taken:

- Updated Karpenter to version 0.5.0.
- Verified that the managed identity is added to the VM.

Despite these steps, I am still encountering the same issue. Could you please provide further assistance on how to resolve this?

**Comment by comtalyst** [comment]
(discussed in https://github.com/Azure/karpenter-provider-azure/issues/411)
