### ISSUE TITLE
Adding subnet selector functionality

### ISSUE THREAD

**Issue by midaslmg94** [Azure/karpenter-provider-azure#333]
### Tell us about your request

I am currently working with the AKSNodeClasses CRD, which only includes the properties imageFamily, imageVersion, osDiskSizeGB, and tags. For enhanced functionality, it would be beneficial to add a subnetSelector property.

This addition would enable scaling nodes within specific subnets, a feature not currently supported by AKSNodeClasses. I noticed that EC2NodeClass already supports this through subnetSelectorTerms (as detailed here: [Karpenter Documentation](https://karpenter.sh/preview/concepts/nodeclasses/#specsubnetselectorterms)). Implementing a similar functionality in AKSNodeClasses could provide more flexibility and control over node deployment in various subnet environments.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

no

### Are you currently working around this issue?

no

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Bryce-Soghigian** [comment]
Hi @midaslmg94  thanks for opening an issue! I am working on adding subnet support per nodeclass. The PR for this is out and can be viewed here: https://github.com/Azure/karpenter-provider-azure/pull/314/files. 

This would allow you to specify a subnet in the AKSNodeClass via the subnets ARM Resource ID. We will not be supporting tags based selection, but you will be able to specify a subnet per nodeclass. 


Is this sufficent? Does it solve for your usecase?

**Comment by pranaypathik** [comment]
I was wondering if this was completed. I can see the pull request is closed but I don't see the changes in the CRD to allow the vnetsubnetid

**Comment by Bryce-Soghigian** [comment]
Hi @pranaypathik, sorry for the delayed response. 

I paused work on subnet support for a bit in favor of security and quality work. We will be addressing this in some form before GA.

**Comment by Bryce-Soghigian** [comment]
Update added support for this here: https://github.com/Azure/karpenter-provider-azure/pull/486
