### ISSUE TITLE
feat: Add support for Azure CNI (w/o overlay)

### ISSUE THREAD

**Issue by Bryce-Soghigian** [Azure/karpenter-provider-azure#367]
### Tell us about your request

Karpenter users should be able to use the Azure CNI without overlay networking.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Currently the only part that karpenter needs to do differently for this support is to generate additional ip configurations for IPAM to consume on the nics we create. 

### Are you currently working around this issue?

no existing workarounds

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Bryce-Soghigian** [comment]
See more details in the PR description linked.

**Comment by johnroach** [comment]
@Bryce-Soghigian I just want to thank you for this work you are doing. I honestly can't wait for this to be done 😄

**Comment by pdeva** [comment]
this is a blocker issue for us. Azure Application Gateway cannot be used when  azure-cni with overlay is enabled. hopefully it gets resolved soon.
