### ISSUE TITLE
Installation script looks for bootstrap token but not found

### ISSUE THREAD

**Issue by darklight147** [Azure/karpenter-provider-azure#430]
### Version

__Karpenter Version:__ v0.0.0

__Kubernetes Version:__ v1.0.0

### Expected Behavior

Installation using steps in the README

### Actual Behavior

fails at the ./configure-values.yml since the script looks for a secret with 
`kubectl get -n kube-system secrets --field-selector=type=bootstrap.kubernetes.io/token`

but doesnt find it, my cluster was created using terraform with the following module

```tf
module "aks" {
  source                = "Azure/aks/azurerm"
  resource_group_name   = var.resource_group_name
  location              = var.location
  kubernetes_version    = var.kubernetes_version
  cluster_name          = var.aks_cluster_name
  admin_username        = "azureuser"
  log_retention_in_days = "30"

  network_plugin = "azure"

  network_plugin_mode = "overlay"

  ebpf_data_plane = "cilium"


  role_based_access_control_enabled = false

  prefix = var.dns_prefix

  oidc_issuer_enabled = true




  node_pools = {
    default = {
      name       = var.default_node_pool_name
      node_count = var.default_node_pool_node_count
      vm_size    = var.default_node_pool_vm_size

    }
  }

  rbac_aad_managed = false

  rbac_aad = false

  sku_tier = var.sku_tier





  identity_type = "SystemAssigned"

  tags = var.tags
}
```

### Steps to Reproduce the Problem

- use the above tf to create an AKS cluster
- follow steps in the README

### Resource Specs and Logs

+ curl -sO https://raw.githubusercontent.com/Azure/karpenter-provider-azure/main/hack/deploy/configure-values.sh
+ chmod +x ./configure-values.sh
+ ./configure-values.sh XXXXXXXX XXXXXX karpenter-sa karpentermsi
Configuring karpenter-values.yaml for cluster XXXXXXX in resource group XXXXXXXX ...
WARNING: The behavior of this command has been altered by the following extension: aks-preview
error: error executing jsonpath "{.items[0].metadata.name}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
        template was:
                {.items[0].metadata.name}
        object given to jsonpath engine was:
                map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":""}}

running the command my self give the following results

<img width="798" alt="image" src="https://github.com/Azure/karpenter-provider-azure/assets/39389636/3de19c3a-a17d-461e-9a78-de2e08c8b79b">

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Bryce-Soghigian** [comment]
We synced on this on linkedin, for others knowledge, I will document the discussion below. 

Note that for self hosted if you perform an upgrade that changes the bootstrapping token, self hosted will need to have that token rotated. Its managed in our managed offering and will go away at some point in the future for self hosted, but thats the state of the world for now. 

----
Mani 6:12 AM:
Hi Bryce, Hope you are doing well. I’m facing an issue with Karpenter in AKS. When my bootstrap token is updated in the kube-system namespace, the nodes are not able to attach to the AKS cluster. Any suggestions? Thanks, Mani

Bryce 3:26 AM:
Is this with self-hosted or the managed offering? Upgrade is not supported yet for self-hosted. You can redeploy with the new token being used in your helm values.

Mani 3:27 AM:
It’s self-hosted. Yep, thanks for the info.

Bryce 3:28 AM:
Let me know if that works.

Mani 3:30 AM:
Yeah, that worked.

**Comment by tpaul1611** [comment]
@Bryce-Soghigian Can you give some guidance on how this is managed for the managed offering?
