### ISSUE TITLE
feat: make IPForwarding a configurable parameter

### ISSUE THREAD

**Issue by c3JpbmkK** [Azure/karpenter-provider-azure#439]
### Tell us about your request

We want to use Karpeter on AKS with Azure CNI powered by Cilium but our network policies from management group level prevents Karpenter from creating nodes as the provider tries to create nodes with IP forwarding set to true.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

We're trying to use Karpenter to provision nodes, but the provider tries to create nodes with IPForwarding set to true always [EnableIPForwarding:          to.Ptr(true)](https://github.com/Azure/karpenter-provider-azure/blob/main/pkg/providers/instance/instance.go#L232C4-L232C46). Provisioning virtual machines with IP forwarding is disallowed by policy in our environment so this is a blocker for us to use Karpenter.

### Are you currently working around this issue?

We're not using Karpenter yet because of this issue. 
But we were able to get it working by explicitly setting the parameter to false in [here](https://github.com/Azure/karpenter-provider-azure/blob/main/pkg/providers/instance/instance.go#L232C4-L232C46), 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tallaxes** [comment]
Based on the internal discussion we decided to just disable IPForwarding altogether; resolved by https://github.com/Azure/karpenter-provider-azure/pull/467
