### ISSUE TITLE
 failed to resolve reference "mcr.microsoft.com/aks/karpenter/controller:latest

### ISSUE THREAD

**Issue by abhishek-baranwal** [Azure/karpenter-provider-azure#496]
### Version

__Karpenter Version:__ v0.0.0

__Kubernetes Version:__ v1.0.0

### Expected Behavior

Hi team,
while using this helm chart we are not able to pull the docker image, its failing with below error
```shell
docker run -it --rm mcr.microsoft.com/aks/karpenter/controller /bin/bash
Unable to find image 'mcr.microsoft.com/aks/karpenter/controller:latest' locally
docker: Error response from daemon: failed to resolve reference "mcr.microsoft.com/aks/karpenter/controller:latest": mcr.microsoft.com/aks/karpenter/controller:latest: not found.
See 'docker run --help'.
``` 

though its working for other images

```shell
 docker run -it --rm mcr.microsoft.com/azurelinux/base/nginx:1 /bin/bash

Unable to find image 'mcr.microsoft.com/azurelinux/base/nginx:1' locally
1: Pulling from azurelinux/base/nginx
25c2aa39953f: Download complete
3f61ac909e65: Download complete
700766794894: Download complete
bf91f2b93eeb: Download complete
fc90c0809940: Download complete
Digest: sha256:a69031ae155177063df515ad53ec0bb52ed4c8f0e00346fc30a018cf81c146b5
Status: Downloaded newer image for mcr.microsoft.com/azurelinux/base/nginx:1
root [ / ]# exit
exit
``` 

### Actual Behavior

It should pull the image anywhere either in AKS or local docker pull

### Steps to Reproduce the Problem

docker pull mcr.microsoft.com/aks/karpenter/controller

### Resource Specs and Logs

Unable to find image 'mcr.microsoft.com/aks/karpenter/controller:latest' locally
docker: Error response from daemon: failed to resolve reference "mcr.microsoft.com/aks/karpenter/controller:latest": mcr.microsoft.com/aks/karpenter/controller:latest: not found.
See 'docker run --help'.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tallaxes** [comment]
Try `mcr.microsoft.com/aks/karpenter/controller:0.5.4` (we don't publish `latest` tag).

**Comment by tallaxes** [comment]
Tags in the MCR portal: No, these are currently not discoverable via portal (we can look into changing that). To determine available tags please use releases from the repo: image tag will be the same as release tag, but without "v" in front.

Dockerfile: The provider is currently not using dockerized build; it uses hack/release scripts, via corresponding GitHub action. (These - would be a good starting point if you want to create dockerized build.) Other ways of building from source yourself would be devcontainer + Skaffold.

Security: If you are aware of any security issues in the repo, please report them following the guidance in SECURITY.md.
