### ISSUE TITLE
panic: creating Azure client: secret can't be empty string when installing self hosted karpenter

### ISSUE THREAD

**Issue by perezmark** [Azure/karpenter-provider-azure#507]
### Version

__Karpenter Version:__ v0.5.4

__Kubernetes Version:__ v1.30.0

### Expected Behavior

working with self hosted installation

### Actual Behavior

azure client error using self hosted installation

### Steps to Reproduce the Problem

followed the self hosted installation only

### Resource Specs and Logs

replicas: 1 # for better debugging experience
controller:
  env:
    - name: FEATURE_GATES
      value: Drift=true
    - name: LEADER_ELECT # disable leader election for better debugging / troubleshooting experience
      value: "false"
    # disable HTTP/2 to reduce ARM throttling on large-scale tests;
    # with this in place write (and read) QPS can be increased too
    #- name: GODEBUG
    #  value: http2client=0
    # options
    - name: CLUSTER_NAME
      value: karpenter
    - name: CLUSTER_ENDPOINT
      value: [https://karpenter-karpenter-5c519e-xxxxxx.hcp.southeastasia.azmk8s.io:443](https://karpenter-karpenter-5c519e-xxxxxx.hcp.southeastasia.azmk8s.io/)
    - name: KUBELET_BOOTSTRAP_TOKEN
      value: 9xgbg4.rxxxxxxxxxni
    - name: SSH_PUBLIC_KEY
      value: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDOrsd6TGFGKnHwxwk4/4ehLRSmCw1fNYWho9UvMVqLmp2tONeH0nb10vsm2UXm3C1EzuFWWv/WdhbfhhM0g5MlOMJ20w4NpKlxOkq0T4XfVenXrXcMHr++/jpWmd5pnJY2qXxzMpFbaxxxxxxxxxx+Tb5kRmkLEJZy9N3d0jbsLieqMTGd7UdrDKYTfMMVr4rhTmp19X6PKVIhGProUMuqWOKLI2/ge7aTO1wgxildshlPB3Ciau6RGSJ9mCN/cVq1vpupDNVqIhDiFZlseZbJp0sERibSdxPHAJcwETBMOtTXT5DvAykUkjB6awSXJkOSagVGLWmbe1Tb18tN123NWjxdvlHx0sgd2CWq5/WAZI4k= xxxxxxl azureuser"
    - name: NETWORK_PLUGIN
      value: azure
    # - name: NETWORK_PLUGIN_MODE
    #   value: overlay
    - name: NETWORK_POLICY
      value: cilium
    - name: VNET_SUBNET_ID
      value: /subscriptions/xxxxx/resourceGroups/MC_karpenter_karpenter_southeastasia/providers/Microsoft.Network/virtualNetworks/aks-vnet-17432186/subnets/aks-subnet
    - name: NODE_IDENTITIES
      value: /subscriptions/xxxxxxxx/resourcegroups/MC_karpenter_karpenter_southeastasia/providers/Microsoft.ManagedIdentity/userAssignedIdentities/karpenter-agentpool
    # Azure client settings
    - name: ARM_SUBSCRIPTION_ID
      value: xxxxxxxxxxxxxx
    - name: LOCATION
      value: southeastasia
    - name: KUBELET_IDENTITY_CLIENT_ID
      value: "616c6767-xxxx-4a0f-xxxx-f42475dd54be"
    - name: AZURE_NODE_RESOURCE_GROUP
      value: MC_karpenter_karpenter_southeastasia
serviceAccount:
  name: karpenter-sa
  annotations:
    azure.workload.identity/client-id: 81940411-xxxx-47cf-xxxx-b8ef21f72174
podLabels:
  azure.workload.identity/use: "true"
I installed this
export KARPENTER_VERSION=0.5.4

helm upgrade --install karpenter oci://mcr.microsoft.com/aks/karpenter/karpenter \
  --version "${KARPENTER_VERSION}" \
  --namespace "${KARPENTER_NAMESPACE}" --create-namespace \
  --values karpenter-values.yaml \
  --set controller.resources.requests.cpu=1 \
  --set controller.resources.requests.memory=1Gi \
  --set controller.resources.limits.cpu=1 \
  --set controller.resources.limits.memory=1Gi \
  --wait

kubectl logs -f -n "${KARPENTER_NAMESPACE}" -l app.kubernetes.io/name=karpenter -c controller
Pulled: mcr.microsoft.com/aks/karpenter/karpenter:0.5.4
Digest: sha256:fb5af9ca612a8d9e40f377093de8f62bc84be4146809e305e2f79573c802c25d
Release "karpenter" has been upgraded. Happy Helming!
NAME: karpenter
LAST DEPLOYED: Wed Oct  2 02:36:50 2024
NAMESPACE: kube-system
STATUS: deployed
REVISION: 10
TEST SUITE: None
Error from server (BadRequest): container "controller" in pod "karpenter-57686777f-pngs5" is waiting to start: ContainerCreating
got this error
┌─────────────────────────────────────────────────────────── Logs(kube-system/karpenter-57686777f-pngs5:controller)[tail] ───────────────────────────────────────────────────────────┐
│                                                         Autoscroll:On      FullScreen:Off     Timestamps:Off     Wrap:Off                                                          │
│ {"level":"DEBUG","time":"2024-10-01T18:39:58.419Z","logger":"controller","message":"loaded log configuration from file \"/etc/karpenter/logging/zap-logger-config\"","commit":"846 │
│ {"level":"DEBUG","time":"2024-10-01T18:39:58.419Z","logger":"controller","message":"discovered karpenter version","commit":"846ef96","version":"unspecified"}                      │
│ panic: creating Azure client: secret can't be empty string                                                                                                                         │
│                                                                                                                                                                                    │
│ goroutine 1 [running]:                                                                                                                                                             │
│ github.com/samber/lo.must({0x1e6c3a0, 0xc000a62d10}, {0xc000867e20, 0x1, 0x1})                                                                                                     │
│     github.com/samber/lo@v1.47.0/errors.go:51 +0x1bb                                                                                                                               │
│ github.com/samber/lo.Must0(...)                                                                                                                                                    │
│     github.com/samber/lo@v1.47.0/errors.go:72                                                                                                                                      │
│ github.com/Azure/karpenter-provider-azure/pkg/operator.NewOperator({0x25934e8, 0xc00088da70}, 0xc000a94120)                                                                        │
│     github.com/Azure/karpenter-provider-azure/pkg/operator/operator.go:74 +0x10b                                                                                                   │
│ main.main()                                                                                                                                                                        │
│     github.com/Azure/karpenter-provider-azure/cmd/controller/main.go:36 +0x2a                                                                                                      │
│ Stream closed EOF for kube-system/karpenter-57686777f-pngs5 (controller)                                                                                                           │
│

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Bryce-Soghigian** [comment]
Not entirely certain, but looks like you are using the image version v0.5.4, but those helm values are using things defined in an unreleased version of karpenter. (NETWORK_PLUGIN_MODE, and recent refactor for USER_ASSIGNED_IDENTITY_ID -> KUBELET_IDENTITY_CLIENT_ID).

We need to come up with a better way to manage the helm values here for self-hosted users. Given the preference is that users use the managed offering.

**Comment by quanhlam** [comment]
Encountering the same issue.. The installation templates that you are using is pinned with main branch which is unreleased. One workaround for now is pin the template with version you are using. For example I use v0.5.4:
1. configure-value.sh file: Download frorm `https://raw.githubusercontent.com/Azure/karpenter-provider-azure/v0.5.4/hack/deploy/configure-values.sh`
2. In the configure-value file, replace `https://raw.githubusercontent.com/Azure/karpenter/main/karpenter-values-template.yaml` with `https://raw.githubusercontent.com/Azure/karpenter/v.0.5.4/karpenter-values-template.yaml`

**Comment by quanhlam** [comment]
Encountering the same issue. The installation templates that you are using is pinned with main branch which is unreleased. They have contain new parameters which may crash current version Karrpenter. One workaround you can do is pin the template with version you are using. For example I use v0.5.4:

configure-value.sh file: Download frorm https://raw.githubusercontent.com/Azure/karpenter-provider-azure/v0.5.4/hack/deploy/configure-values.sh
In the configure-value file, replace https://raw.githubusercontent.com/Azure/karpenter/main/karpenter-values-template.yaml with https://raw.githubusercontent.com/Azure/karpenter/v.0.5.4/karpenter-values-template.yaml

**Comment by quanhlam** [comment]
Encountering the same issue. The installation templates that you are using is pinned with main branch which is unreleased. They have contain new parameters which may crash current version Karrpenter. One workaround you can do is pin the template with version you are using. For example I use v0.5.4:

1. configure-value.sh file: Download frorm https://raw.githubusercontent.com/Azure/karpenter-provider-azure/v0.5.4/hack/deploy/configure-values.sh
2. In the configure-value file, replace https://raw.githubusercontent.com/Azure/karpenter/main/karpenter-values-template.yaml with https://raw.githubusercontent.com/Azure/karpenter/v.0.5.4/karpenter-values-template.yaml

**Comment by quanhlam** [comment]
Encountering the same issue. The installation templates that you are using is pinned with main branch which is unreleased. They have contain new parameters which may crash current version Karpenter. One workaround you can do is pin the template with version you are using. For example I use v0.5.4:

configure-value.sh file: Download from https://raw.githubusercontent.com/Azure/karpenter-provider-azure/v0.5.4/hack/deploy/configure-values.sh
In the configure-value file, replace https://raw.githubusercontent.com/Azure/karpenter/main/karpenter-values-template.yaml with https://raw.githubusercontent.com/Azure/karpenter/v.0.5.4/karpenter-values-template.yaml

**Comment by quanhlam** [comment]
Encountering the same issue. The installation templates that you are using are pinned with main branch which is unreleased. They have new parameters which may crash current version Karpenter. One workaround you can do is pin the template with version you are using. For example I use v0.5.4:

configure-value.sh file: Download from https://raw.githubusercontent.com/Azure/karpenter-provider-azure/v0.5.4/hack/deploy/configure-values.sh
In the configure-value file, replace https://raw.githubusercontent.com/Azure/karpenter/main/karpenter-values-template.yaml with https://raw.githubusercontent.com/Azure/karpenter/v.0.5.4/karpenter-values-template.yaml

**Comment by quanhlam** [comment]
Encountering the same issue. The installation templates that you are using are pinned with main branch which is unreleased. They have new parameters which may crash current version Karpenter. One workaround you can do is pin the template with version you are using. For example I use v0.5.4:

1. configure-value.sh file: Download from https://raw.githubusercontent.com/Azure/karpenter-provider-azure/v0.5.4/hack/deploy/configure-values.sh
2. In the configure-value file, replace https://raw.githubusercontent.com/Azure/karpenter/main/karpenter-values-template.yaml with https://raw.githubusercontent.com/Azure/karpenter/v.0.5.4/karpenter-values-template.yaml

**Comment by gmtborges** [comment]
> Encountering the same issue. The installation templates that you are using are pinned with main branch which is unreleased. They have new parameters which may crash current version Karpenter. One workaround you can do is pin the template with version you are using. For example I use v0.5.4:
> 
> 1. configure-value.sh file: Download from https://raw.githubusercontent.com/Azure/karpenter-provider-azure/v0.5.4/hack/deploy/configure-values.sh
> 2. In the configure-value file, replace https://raw.githubusercontent.com/Azure/karpenter/main/karpenter-values-template.yaml with https://raw.githubusercontent.com/Azure/karpenter/v.0.5.4/karpenter-values-template.yaml

I tried these suggestions, but didn't work for me. I still got the same error 

```
panic: creating Azure client: secret can't be empty string

goroutine 1 [running]:
github.com/samber/lo.must({0x191e1e0, 0x40007be5b0}, {0x4000897e18, 0x1, 0x1})
        github.com/samber/lo@v1.47.0/errors.go:51 +0x1a8
github.com/samber/lo.Must0(...)
        github.com/samber/lo@v1.47.0/errors.go:72
github.com/Azure/karpenter-provider-azure/pkg/operator.NewOperator({0x2045c78, 0x400094ced0}, 0x400085ba40)
        github.com/Azure/karpenter-provider-azure/pkg/operator/operator.go:74 +0xd4
main.main()
        github.com/Azure/karpenter-provider-azure/cmd/controller/main.go:36 +0x28
```

**Comment by perezmark** [comment]
This is working with me already using the workload identity 

i just added this Envs in the values.yaml

- name: ARM_USE_CREDENTIAL_FROM_ENVIRONMENT
  value: "true"
- name: ARM_CLIENT_SECRET
  value: "test"


In the/karpenter-provider-azure/pkg/auth/config.go (tag v0.5.4)

we can see that these are used
