### ISSUE TITLE
Karpentern VM's not Spinning up due to OS and data disks should be encrypted with a customer-managed key

### ISSUE THREAD

**Issue by divyanjali1** [Azure/karpenter-provider-azure#536]
I have a kubernetes cluster running on k8s version 1.29 
Recently deployed self managed karpenter v0.5.4 , and running into below issue 
OS and data disks should be encrypted with a customer-managed key

Can someone please suggest what varibles to passed in karpenter-values.yaml to resolve this ?

**Comment by Bryce-Soghigian** [comment]
Thanks for writing an issue!!!! 

Can you please provide more details of the existing AKS experience and what is expected of parity with karpenter?

**Comment by tallaxes** [comment]
Disk encryption is currently not supported, see https://github.com/Azure/karpenter-provider-azure/issues/268, let's track it there (and feel free to add your vote and/or use case there)
