### ISSUE TITLE
Karpenter Node Creation Fails with "Node not registered with cluster" on Azure AKS with Azure CNI and Calico

### ISSUE THREAD

**Issue by amirfatemiichoosr** [Azure/karpenter-provider-azure#571]
### Version

__Karpenter Version:__ v0.7.0

__Kubernetes Version:__ v1.30.5

### Expected Behavior

Karpenter should successfully create and register new nodes in the AKS cluster, bringing them to a "Ready" state for workloads.

### Actual Behavior

Karpenter creates new nodes, but they remain in an "Initialized" state and fail to register with the cluster. The status for "Ready" displays UnhealthyDependents, and messages indicate "Node not registered with cluster."

### Steps to Reproduce the Problem

1. Configure an AKS cluster with the following settings:
- OS: AzureLinux
- Network configuration: Azure CNI Node Subnet
- Network policy: Calico

2. Deploy Karpenter on the AKS cluster using Terraform.
3. Create an AKSNodeClass and a NodePool.
4 Request a node through a NodeClaim.
5. Observe the status of the new node.

### Resource Specs and Logs

Node Logs:

```
- lastTransitionTime: '2024-11-11T18:25:14Z'
  message: Node not registered with cluster
  reason: NodeNotFound
  status: Unknown
  type: Initialized
- lastTransitionTime: '2024-11-11T18:25:14Z'
  message: ''
  reason: Launched
  status: 'True'
  type: Launched
- lastTransitionTime: '2024-11-11T18:25:14Z'
  message: Initialized=Unknown, Registered=Unknown
  reason: UnhealthyDependents
  status: Unknown
  type: Ready
```

Karpenter log pod: 

```
{"level":"info","ts":1731348521.1395092,"logger":"fallback","caller":"instance/instance.go:152","msg":"launched new instance","launched-instance":"/subscriptions/***/resourceGroups/****/providers/Microsoft.Compute/virtualMachines/aks-general-purpose-79mc9","hostname":"aks-general-purpose-79mc9","type":"Standard_D4ls_v5","zone":"3","capacity-type":"on-demand"}
{"level":"INFO","time":"2024-11-11T18:08:41.139Z","logger":"controller","caller":"lifecycle/launch.go:61","message":"launched nodeclaim","commit":"d83a94c","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"general-purpose-79mc9"},"namespace":"","name":"general-purpose-79mc9","reconcileID":"***","provider-id":"azure:///subscriptions/***/resourceGroups/****/providers/Microsoft.Compute/virtualMachines/aks-general-purpose-79mc9","instance-type":"Standard_D4ls_v5","zone":"","capacity-type":"on-demand","allocatable":{"cpu":"3860m","ephemeral-storage":"128G","memory":"5226731929","pods":"110"}}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Bryce-Soghigian** [comment]
We do not support calico at this time.

**Comment by Bryce-Soghigian** [comment]
Don't support calico
