### ISSUE TITLE
Timeline for Node Auto Provisioning in AKS Reaching GA

### ISSUE THREAD

**Issue by bedij03** [Azure/karpenter-provider-azure#582]
Hi,
I’ve been exploring the Node Auto Provisioning mode for Azure Kubernetes Service (AKS), and I find it a promising feature for optimizing scaling. However, I’d like to know:

Is there an estimated timeline for when Node Auto Provisioning is expected to reach General Availability (GA)?
Are there any specific blockers or known areas of improvement being addressed before GA?
I’d appreciate any updates or insights on this feature's roadmap.

Thanks!

**Comment by tallaxes** [comment]
Please use the public roadmap issue for any questions on updates specific to NAP: https://github.com/Azure/AKS/issues/2442
Generally though, the remaining work is mostly around quality, reliability and observability.
