### ISSUE TITLE
Tag network interfaces with `karpenter.sh_nodepool`

### ISSUE THREAD

**Issue by philwelz** [Azure/karpenter-provider-azure#75]
### Tell us about your request

all resources created by the Karpenter provider should have consistent tags in Azure. For example: `karpenter.azure.com_cluster` & `karpenter.sh_nodepool`.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Tag und Label consistency for calls like `az resource list --tag=karpenter.sh_nodepool` or `az resource list --tag=karpenter.azure.com_cluster`. At the moment disks & vms get both tags assigned but nics only have the tag `karpenter.azure.com_cluster`.

### Are you currently working around this issue?

Only working with the label / tag `karpenter.azure.com_cluster`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by rajendar38** [comment]
Hi Phil , I am interested work on this issue, could you please help me on more details how could I start

**Comment by tallaxes** [comment]
@rajendar38, here is how this tag is applied to VMs, need something similar for network interfaces:
https://github.com/Azure/karpenter/blob/54393d0e09ab4eff90590659a046e886e69201a4/pkg/providers/instance/instance.go#L361

**Comment by Bryce-Soghigian** [comment]
@rajendar38  if you have any other questions feel free to message me in the k8s slack as well. Would love to see your contribution!

**Comment by rajendar38** [comment]
I am able to create cluster now , But I did not see any resources like nice , Vms or disk created.
I see two resource groups created 
1)karpenter. with resources : SERVICE AND CONTAINER REGISTRY 
2)MC_karpenter_karpenter_eastus:

<img width="718" alt="Screenshot 2023-12-23 at 9 26 59 PM" src="https://github.com/Azure/karpenter/assets/7486976/f2dd0809-eca3-436d-bd45-5aa125599417">

**Comment by Bryce-Soghigian** [comment]
@rajendar38, you need karpenter to scale up to create nodes. 


if you ran `make az-all` it should have applied the command `make az-run-sample` which will have deployed a sample nodepool and deployment. 

Run
```
kubectl taint nodes CriticalAddonsOnly=true:NoSchedule --all --overwrite
`kubectl scale deployment inflate --replicas 1
```

Which will give you a single small karpenter node. From there, you want to inspect the nic's azure tags. 


in the azure tags, what we are trying to achieve is that you add the karpenter.sh_nodepool tag to the network interface.


Currently 100% of the time we do not.

**Comment by rajendar38** [comment]
ajendar@rajendars-mbp docs % kubectl scale deployment inflate --replicas 1
error: no objects passed to scale

**Comment by Bryce-Soghigian** [comment]
@rajendar38  looks like the you haven't installed the CRDs. 

How did you configure karpenter to run? 

`make az-all` which will create an AKS Cluster, install karpenter, etc should have installed the CRDs.

**Comment by Bryce-Soghigian** [comment]
@rajendar38  any blockers we can help with?

**Comment by rajendar38** [comment]
@Bryce-Soghigian I have installed through `make az-all` , but CRD are not installed .
I am unable to replicate the issue in my azure subscription which I have currently .

**Comment by iamvighnesh** [comment]
@rajendar38 let me know if you'd like to pair program on this one. I have some time to dedicate for this.

**Comment by rajendar38** [comment]
> @rajendar38 let me know if you'd like to pair program on this one. I have some time to dedicate for this.

Sure

**Comment by iamvighnesh** [comment]
> > @rajendar38 let me know if you'd like to pair program on this one. I have some time to dedicate for this.
> 
> Sure

@rajendar38 I have reached out to you on kubernetes.slack.com. I have also had a look at where the changes could be made. Let's pick up the conversation there.

@Bryce-Soghigian I feel a change in [here](https://github.com/Azure/karpenter-provider-azure/blob/2621c0d49f6dcc3608d9b3e279db0436f81a8bf4/pkg/providers/instance/instance.go#L502) would propagate the tags across all resources that will use the `launchTemplate` going forward:

`additionalLabels := lo.Assign(GetAllSingleValuedRequirementLabels(instanceType), map[string]string{corev1beta1.CapacityTypeLabelKey: capacityType, corev1beta1.NodePoolLabelKey: nodeClaim.Name})`

Let me know what you think.

**Comment by Bryce-Soghigian** [comment]
@iamvighnesh  please feel free to make a pr for this as I know you are interested in contributing to our project
