### ISSUE TITLE
LowPriorityCoresQuota error should mark spot as unavailable

### ISSUE THREAD

**Issue by ottodeng** [Azure/karpenter-provider-azure#91]
### Tell us about your request

Any roadmap to support scale spot node fail, and fallback to on-demand node? 

I saw Karpenter is AWS already easy to support.
https://github.com/aws/karpenter-provider-aws/blob/e00c97c3c834a1349a4126f69500fdcc4caf1344/website/content/en/v0.32/faq.md?plain=1#L82

but in Azure, if the spot instance cannot created succuess, that will crash, cannot failback to on-demand.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

to save the cost, balance the spot and on-demand resources.

### Are you currently working around this issue?

no

### Additional Context

![image](https://github.com/Azure/karpenter/assets/20509364/ed1ce8e1-b28a-432e-8cd9-13342177d7db)
Tested on Azure, I create a deployment with 4 gpu pod. And I only have 3 gpu spot quota.
As design, it will create the fourth node with on-demand, but now always crash in the fourth node in spot.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ottodeng** [comment]
(base) ottodeng@STNCEATS01:/Users/ottodeng/aks $ kubectl get nodeclaims.karpenter.sh
NAME             TYPE                       ZONE              NODE                 READY   AGE
gpu-spot-9bhv2   Standard_NC24ads_A100_v4   southeastasia-3   aks-gpu-spot-9bhv2   True    7m26s
gpu-spot-h9ffv                                                                     False   7m26s
gpu-spot-mfrvr   Standard_NC24ads_A100_v4   southeastasia-3   aks-gpu-spot-mfrvr   True    7m26s
gpu-spot-mwvmj   Standard_NC24ads_A100_v4   southeastasia-3   aks-gpu-spot-mwvmj   True    8m51s
(base) ottodeng@STNCEATS01:/Users/ottodeng/aks $ kubectl describe nodeclaims.karpenter.sh gpu-spot-h9ffv 
Name:         gpu-spot-h9ffv
Namespace:    
Labels:       karpenter.sh/nodepool=gpu-spot
Annotations:  karpenter.sh/nodepool-hash: 14131116538321825039
API Version:  karpenter.sh/v1beta1
Kind:         NodeClaim
Metadata:
  Creation Timestamp:  2024-01-17T00:20:30Z
  Finalizers:
    karpenter.sh/termination
  Generate Name:  gpu-spot-
  Generation:     1
  Managed Fields:
    API Version:  karpenter.sh/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:karpenter.sh/nodepool-hash:
        f:finalizers:
          .:
          v:"karpenter.sh/termination":
        f:generateName:
        f:labels:
          .:
          f:karpenter.sh/nodepool:
        f:ownerReferences:
          .:
          k:{"uid":"84b3fe10-9c60-476a-be09-b53f62421fd6"}:
      f:spec:
        .:
        f:nodeClassRef:
          .:
          f:name:
        f:requirements:
        f:resources:
          .:
          f:requests:
            .:
            f:cpu:
            f:memory:
            f:nvidia.com/gpu:
            f:pods:
        f:taints:
    Manager:      karpenter
    Operation:    Update
    Time:         2024-01-17T00:20:30Z
    API Version:  karpenter.sh/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
    Manager:      karpenter
    Operation:    Update
    Subresource:  status
    Time:         2024-01-17T00:20:48Z
  Owner References:
    API Version:           karpenter.sh/v1beta1
    Block Owner Deletion:  true
    Kind:                  NodePool
    Name:                  gpu-spot
    UID:                   84b3fe10-9c60-476a-be09-b53f62421fd6
  Resource Version:        3564308
  UID:                     863c890f-60b5-4b16-98f5-951d774f5ec6
Spec:
  Node Class Ref:
    Name:  gpu-spot
  Requirements:
    Key:       karpenter.azure.com/sku-name
    Operator:  In
    Values:
      Standard_NC24ads_A100_v4
    Key:       karpenter.azure.com/sku-gpu-manufacturer
    Operator:  In
    Values:
      nvidia
    Key:       karpenter.sh/nodepool
    Operator:  In
    Values:
      gpu-spot
    Key:       node.kubernetes.io/instance-type
    Operator:  In
    Values:
      Standard_NC24ads_A100_v4
    Key:       kubernetes.io/arch
    Operator:  In
    Values:
      amd64
    Key:       kubernetes.io/os
    Operator:  In
    Values:
      linux
    Key:       karpenter.sh/capacity-type
    Operator:  In
    Values:
      on-demand
      spot
  Resources:
    Requests:
      Cpu:             250m
      Memory:          470Mi
      nvidia.com/gpu:  1
      Pods:            7
  Taints:
    Effect:  NoSchedule
    Key:     nvidia.com/gpu
    Value:   true
Status:
  Conditions:
    Last Transition Time:  2024-01-17T00:20:48Z
    Message:               Node not launched
    Reason:                NotLaunched
    Status:                False
    Type:                  Initialized
    Last Transition Time:  2024-01-17T00:20:48Z
    Message:               creating instance, virtualMachine.BeginCreateOrUpdate for VM "aks-gpu-spot-h9ffv" failed: PUT https://management.azure.com/subscriptions/2a5e7fa2-d528-4c66-9e6a-3a3a0f290e98/resourceGroups/MC_rg-aks-nap-sg_aks-nap-sg_southeastasia/providers/Microsoft.Compute/virtualMachines/aks-gpu-spot-h9ffv
------...
    Reason:                LaunchFailed
    Status:                False
    Type:                  Launched
    Last Transition Time:  2024-01-17T00:20:48Z
    Message:               Node not launched
    Reason:                NotLaunched
    Status:                False
    Type:                  Ready
    Last Transition Time:  2024-01-17T00:20:48Z
    Message:               Node not launched
    Reason:                NotLaunched
    Status:                False
    Type:                  Registered
Events:                    <none>

**Comment by Bryce-Soghigian** [comment]
I was able to repro your case, and looks like you are hitting a LowPriorityCoresQuota error. It seems when we run out of regional spot capacity karpenter today doesn't fall back into on demand. 

To solve this problem, we will need to mark spot instances as unavailable in the unavailable offerings cache. 

Adding a check [here](https://github.com/Azure/karpenter/blob/main/pkg/providers/instance/instance.go#L419) for LowPriorityCores errors , then if we see one we can mark the capacity for spot as unavailable should allow karpenter to fall back properly onto on demand

**Comment by Bryce-Soghigian** [comment]
@ottodeng  my pr should add support for the exact case you are asking for, it will appear in the next nap release. If you wish to play with it you can setup a dev environment off of master. Thanks!

**Comment by Bryce-Soghigian** [comment]
Hey @ottodeng  https://github.com/Azure/karpenter-provider-azure/releases/tag/v0.3.0 the latest release will include it. If you check the releases page we went a long time without a release. (Dec 3rd -> 2 weeks ago). 

This change should be rolling out in southeastasia soon. Let me check that timeline for you!

**Comment by ottodeng** [comment]
@Bryce-Soghigian thanks for reply, is there anyway to check created AKS using which version about https://github.com/Azure/karpenter-provider-azure?
